/**
 * Drizzle schema: campaigns (sqlite)
 * Generated by openspec apply-change.
 * Adjust imports to match your Drizzle setup.
 */
import { sqliteTable, integer, text, timestamp, boolean } from "drizzle-orm/sqlite-core";

export const campaigns = sqliteTable("campaigns", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  brand: text("brand").notNull(),
  model: text("model").notNull(),
  monthly_price: integer("monthly_price").notNull(),
  downpayment: integer("downpayment").notNull(),
  duration_months: integer("duration_months").notNull(),
  km_per_year: integer("km_per_year").notNull(),
  campaign_type: text("campaign_type").notNull(),
  verified: boolean("verified").notNull().default(false),
  valid_from: text("valid_from").notNull(),
  valid_to: text("valid_to").notNull(),
  source_url: text("source_url"),
  image: text("image").notNull(),
  created_at: timestamp("created_at").notNull().defaultNow(),
  updated_at: timestamp("updated_at").notNull().defaultNow(),
});
