/**
 * Drizzle schema: leads (sqlite)
 * Generated by openspec apply-change.
 */
import { sqliteTable, integer, text, timestamp } from "drizzle-orm/sqlite-core";

export const leads = sqliteTable("leads", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  campaign_id: integer("campaign_id").notNull(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  created_at: timestamp("created_at").notNull().defaultNow(),
});

// Note: add a foreign key relationship in migrations (ON DELETE CASCADE)
