BEGIN TRANSACTION;
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Skoda V60 - Gunstig leasing','Skoda','V60',5444,9820,36,15000,'Privat',0,'2026-02-06','2026-11-24',NULL,'https://pics.example/0.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Per Pedersen','per.pedersen@example.no','+4766524050');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ola Hansen','ola.hansen@example.no','+4766716042');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Olsen','lars.olsen@example.no','+4791936699');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Kari Haugen','kari.haugen@example.no','+4790007428');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Tesla V60 - Gunstig leasing','Tesla','V60',7317,8434,48,20000,'Privat',1,'2026-02-06','2026-06-07',NULL,'https://pics.example/1.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Morten Johansen','morten.johansen@example.no','+4756540507');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Hansen','lars.hansen@example.no','+4727241910');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Ford X1 - Gunstig leasing','Ford','X1',4106,3757,48,10000,'Næring',1,'2026-02-06','2026-07-05',NULL,'https://pics.example/2.jpg');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Toyota X1 - Gunstig leasing','Toyota','X1',8250,12517,48,15000,'Privat',1,'2026-02-06','2026-06-19',NULL,'https://pics.example/3.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Morten Berg','morten.berg@example.no','+4747559121');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Jon Johansen','jon.johansen@example.no','+4766919440');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Jon Haugen','jon.haugen@example.no','+4780495528');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Johansen','lars.johansen@example.no','+4790878037');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ingrid Berg','ingrid.berg@example.no','+4798432487');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('BMW Corolla - Gunstig leasing','BMW','Corolla',5948,4675,24,20000,'Privat',1,'2026-02-06','2027-01-17',NULL,'https://pics.example/4.jpg');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Ford Golf - Gunstig leasing','Ford','Golf',8437,8791,48,15000,'Næring',0,'2026-02-06','2026-12-08',NULL,'https://pics.example/5.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Johansen','lars.johansen@example.no','+4799598134');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Kari Johansen','kari.johansen@example.no','+4773077435');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ingrid Nilsen','ingrid.nilsen@example.no','+4752205358');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ingrid Johansen','ingrid.johansen@example.no','+4745377635');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Audi Golf - Gunstig leasing','Audi','Golf',5262,5578,48,10000,'Privat',1,'2026-02-06','2026-12-23',NULL,'https://pics.example/6.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Anne Olsen','anne.olsen@example.no','+4744336969');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Per Andersen','per.andersen@example.no','+4746506957');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Kari Pedersen','kari.pedersen@example.no','+4793810461');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Volvo Ceed - Gunstig leasing','Volvo','Ceed',6255,4183,24,20000,'Privat',0,'2026-02-06','2026-10-12',NULL,'https://pics.example/7.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Karlsen','lars.karlsen@example.no','+4764167231');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('VW Golf - Gunstig leasing','VW','Golf',6712,4952,48,20000,'Privat',0,'2026-02-06','2026-12-18',NULL,'https://pics.example/8.jpg');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Audi A3 - Gunstig leasing','Audi','A3',4063,5779,48,15000,'Privat',0,'2026-02-06','2027-01-25',NULL,'https://pics.example/9.jpg');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Audi Model 3 - Gunstig leasing','Audi','Model 3',7671,7461,48,10000,'Næring',0,'2026-02-06','2026-10-10',NULL,'https://pics.example/10.jpg');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Tesla Octavia - Gunstig leasing','Tesla','Octavia',5035,9196,36,10000,'Privat',0,'2026-02-06','2026-12-19',NULL,'https://pics.example/11.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ola Berg','ola.berg@example.no','+4790344193');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Eva Andersen','eva.andersen@example.no','+4798883699');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ola Karlsen','ola.karlsen@example.no','+4745936764');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Morten Hansen','morten.hansen@example.no','+4778025172');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Kari Johansen','kari.johansen@example.no','+4780160991');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Hyundai A3 - Gunstig leasing','Hyundai','A3',8976,18012,24,15000,'Privat',1,'2026-02-06','2026-11-25',NULL,'https://pics.example/12.jpg');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Ford Ceed - Gunstig leasing','Ford','Ceed',7531,14086,48,15000,'Privat',1,'2026-02-06','2026-08-10',NULL,'https://pics.example/13.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ingrid Olsen','ingrid.olsen@example.no','+4771687522');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Skoda X1 - Gunstig leasing','Skoda','X1',7328,8479,48,15000,'Næring',1,'2026-02-06','2026-12-08',NULL,'https://pics.example/14.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Sofie Olsen','sofie.olsen@example.no','+4784415001');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Eva Nilsen','eva.nilsen@example.no','+4727422147');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Sofie Karlsen','sofie.karlsen@example.no','+4770604538');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Eva Hansen','eva.hansen@example.no','+4748955513');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Sofie Nilsen','sofie.nilsen@example.no','+4727024957');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('VW V60 - Gunstig leasing','VW','V60',7242,9123,24,15000,'Næring',0,'2026-02-06','2026-12-11',NULL,'https://pics.example/15.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Morten Pedersen','morten.pedersen@example.no','+4782359064');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Olsen','lars.olsen@example.no','+4745725324');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Ola Hansen','ola.hansen@example.no','+4782859236');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Volvo Octavia - Gunstig leasing','Volvo','Octavia',4696,7253,36,15000,'Næring',0,'2026-02-06','2026-07-27',NULL,'https://pics.example/16.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Haugen','lars.haugen@example.no','+4748513526');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Volvo V60 - Gunstig leasing','Volvo','V60',5354,1726,36,20000,'Næring',1,'2026-02-06','2026-04-02',NULL,'https://pics.example/17.jpg');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Skoda Model 3 - Gunstig leasing','Skoda','Model 3',5133,3616,48,20000,'Næring',1,'2026-02-06','2027-02-04',NULL,'https://pics.example/18.jpg');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Kari Johansen','kari.johansen@example.no','+4748464628');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Jon Andersen','jon.andersen@example.no','+4789583941');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Eva Andersen','eva.andersen@example.no','+4760613981');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Lars Berg','lars.berg@example.no','+4771503217');
INSERT INTO leads (campaign_id,name,email,phone) VALUES (last_insert_rowid(),'Kari Olsen','kari.olsen@example.no','+4768720592');
INSERT INTO campaigns (title,brand,model,monthly_price,downpayment,duration_months,km_per_year,campaign_type,verified,valid_from,valid_to,source_url,image) VALUES ('Toyota Octavia - Gunstig leasing','Toyota','Octavia',7520,19747,24,15000,'Privat',0,'2026-02-06','2026-12-24',NULL,'https://pics.example/19.jpg');
INSERT OR IGNORE INTO seed_runs (marker) VALUES ('dbseed_v1');
COMMIT;